apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::867757353028:role/stage-diplomproject-eks-iam-role-worker
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::867757353028:user/jvakadinov@tu-sofia.bg
      username: dani
      groups:
        - system:masters
    - userarn: arn:aws:iam::867757353028:user/rlt-tf-user
      username: yordan
      groups:
        - system:masters
  